name: Split monorepo in multiple repositories

on:
  push:
    branches:
      - 0.x
    tags:
      - 'v*'
  delete:
    tags:
      - 'v*'

jobs:
  split:
    runs-on: ubuntu-22.04
    name: Split
    steps:
      - uses: actions/checkout@v3
        with:
          token:  ${{ secrets.DEPLOY_TOKEN_SPLIT }}
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run split command
        run: bash bin/split.sh
        shell: bash
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          DEPLOY_TOKEN_SPLIT: ${{ secrets.DEPLOY_TOKEN_SPLIT }}